import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TopBar } from "@/components/util/top-bar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className + " " + "w-screen h-screen flex justify-center overflow-hidden "}>
                <TopBar></TopBar>
                <div className=" max-w-2xl w-full min-h-screen bg-background  flex justify-center">{children}</div>
            </body>
        </html>
    );
}
